version: 0.2

env:
  variables:
    ELIXIR_VERSION: 1.7.3-otp-21

phases:
  install:
    commands:
      - wget https://repo.hex.pm/builds/elixir/v$ELIXIR_VERSION.zip
      - unzip -d /usr/local/elixir v$ELIXIR_VERSION.zip
      - export PATH=/usr/local/elixir/bin:$PATH
      - mix local.hex --force
      - mix local.rebar --force
      - mix archive.install hex nerves_bootstrap "~> 1.0" --force

  build:
    commands:
      - mix deps.get
      - mix compile
      - mkdir /releases
      - mix nerves.artifact --path /releases
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - /releases/*
